using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Prova.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;

namespace Prova.Generators.Emission
{
    internal static class SourceEmitter
    {
        public static void Execute(SourceProductionContext context, ImmutableArray<TestMethodModel?> methods, List<string?> configMethods, 
            List<(string? Method, bool IsAsync, string? ExecutorType)> beforeAssembly, 
            List<(string? Method, bool IsAsync, string? ExecutorType)> afterAssembly,
            List<(string? Method, bool IsAsync, string? ExecutorType)>? beforeEveryTest = null,
            List<(string? Method, bool IsAsync, string? ExecutorType)>? afterEveryTest = null,
            List<(string? Method, bool IsAsync, string? ExecutorType)>? beforeEveryClass = null,
            List<(string? Method, bool IsAsync, string? ExecutorType)>? afterEveryClass = null,
            int? globalMaxParallel = null,
            List<string?>? factories = null)
        {
            if (methods.IsDefaultOrEmpty && (factories == null || factories.Count == 0)) return;

            // Collect all unique executors for AOT registration
            var executors = methods.Where(m => m != null).Select(m => m!.TestExecutorType)
                .Concat(methods.Where(m => m != null).SelectMany(m => m!.LifecycleBefore.Select(h => h.ExecutorType)))
                .Concat(methods.Where(m => m != null).SelectMany(m => m!.LifecycleAfter.Select(h => h.ExecutorType)))
                .Concat(methods.Where(m => m != null).SelectMany(m => m!.ClassBefore.Select(h => h.ExecutorType)))
                .Concat(methods.Where(m => m != null).SelectMany(m => m!.ClassAfter.Select(h => h.ExecutorType)))
                .Concat(beforeAssembly.Select(h => h.ExecutorType))
                .Concat(afterAssembly.Select(h => h.ExecutorType))
                .Concat(beforeEveryTest?.Select(h => h.ExecutorType) ?? Enumerable.Empty<string?>())
                .Concat(afterEveryTest?.Select(h => h.ExecutorType) ?? Enumerable.Empty<string?>())
                .Concat(beforeEveryClass?.Select(h => h.ExecutorType) ?? Enumerable.Empty<string?>())
                .Concat(afterEveryClass?.Select(h => h.ExecutorType) ?? Enumerable.Empty<string?>())
                .Where(e => !string.IsNullOrEmpty(e))
                .Distinct()
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable CS8601, CS8618, CS8629, CS1591");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Collections.Concurrent;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Prova;");
            sb.AppendLine("using Prova.Reporters;");
            sb.AppendLine("using Prova.Core;");
            sb.AppendLine("using Microsoft.Testing.Platform.Builder;");
            sb.AppendLine("using Microsoft.Testing.Platform.Extensions;");
            sb.AppendLine("using Microsoft.Testing.Extensions;");
            sb.AppendLine();
            sb.AppendLine("namespace Prova");
            sb.AppendLine("{");
            sb.AppendLine("    public static class TestRunnerExecutor");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Global Service Container.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static ProvaServiceProvider Services { get; } = new ProvaServiceProvider();");
            sb.AppendLine();

            // Generate global hook delegate lists
            sb.AppendLine("        private static readonly List<Func<global::System.Threading.Tasks.Task>> _beforeEveryTest = new List<Func<global::System.Threading.Tasks.Task>>() {");
            if (beforeEveryTest != null)
            {
                foreach (var hook in beforeEveryTest.Where(h => !string.IsNullOrEmpty(h.Method)))
                {
                    string executorType = hook.ExecutorType != null ? $"typeof({hook.ExecutorType})" : "null";
                    string hookAction = hook.IsAsync ? $"async () => await {hook.Method}()" : $"() => {{ {hook.Method}(); return global::System.Threading.Tasks.Task.CompletedTask; }}";
                    sb.AppendLine($"            async () => await TestRunnerExecutor.InvokeHookHelper({hookAction}, \"{hook.Method}\", {executorType}),");
                }
            }
            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        private static readonly List<Func<global::System.Threading.Tasks.Task>> _afterEveryTest = new List<Func<global::System.Threading.Tasks.Task>>() {");
            if (afterEveryTest != null)
            {
                foreach (var hook in afterEveryTest.Where(h => !string.IsNullOrEmpty(h.Method)))
                {
                    string executorType = hook.ExecutorType != null ? $"typeof({hook.ExecutorType})" : "null";
                    string hookAction = hook.IsAsync ? $"async () => await {hook.Method}()" : $"() => {{ {hook.Method}(); return global::System.Threading.Tasks.Task.CompletedTask; }}";
                    sb.AppendLine($"            async () => await TestRunnerExecutor.InvokeHookHelper({hookAction}, \"{hook.Method}\", {executorType}),");
                }
            }
            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        private static readonly List<Func<global::System.Threading.Tasks.Task>> _beforeEveryClass = new List<Func<global::System.Threading.Tasks.Task>>() {");
            if (beforeEveryClass != null)
            {
                foreach (var hook in beforeEveryClass.Where(h => !string.IsNullOrEmpty(h.Method)))
                {
                    string executorType = hook.ExecutorType != null ? $"typeof({hook.ExecutorType})" : "null";
                    string hookAction = hook.IsAsync ? $"async () => await {hook.Method}()" : $"() => {{ {hook.Method}(); return global::System.Threading.Tasks.Task.CompletedTask; }}";
                    sb.AppendLine($"            async () => await TestRunnerExecutor.InvokeHookHelper({hookAction}, \"{hook.Method}\", {executorType}),");
                }
            }
            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        private static readonly List<Func<global::System.Threading.Tasks.Task>> _afterEveryClass = new List<Func<global::System.Threading.Tasks.Task>>() {");
            if (afterEveryClass != null)
            {
                foreach (var hook in afterEveryClass.Where(h => !string.IsNullOrEmpty(h.Method)))
                {
                    string executorType = hook.ExecutorType != null ? $"typeof({hook.ExecutorType})" : "null";
                    string hookAction = hook.IsAsync ? $"async () => await {hook.Method}()" : $"() => {{ {hook.Method}(); return global::System.Threading.Tasks.Task.CompletedTask; }}";
                    sb.AppendLine($"            async () => await TestRunnerExecutor.InvokeHookHelper({hookAction}, \"{hook.Method}\", {executorType}),");
                }
            }
            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        private static T? GetExecutorHelper<T>(global::System.Type? type) where T : class");
            sb.AppendLine("        {");
            sb.AppendLine("            if (type == null) return null;");
            sb.AppendLine();
            sb.AppendLine("            // Resolve from Services");
            sb.AppendLine("            return Services.BuildServiceProvider().GetService(type) as T;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async global::System.Threading.Tasks.Task InvokeHookHelper(global::System.Func<global::System.Threading.Tasks.Task> hookAction, string hookName, global::System.Type? executorType)");
            sb.AppendLine("        {");
            sb.AppendLine("            var executor = GetExecutorHelper<IHookExecutor>(executorType);");
            sb.AppendLine("            if (executor != null)");
            sb.AppendLine("            {");
            sb.AppendLine("                await executor.ExecuteAsync(hookAction, hookName);");
            sb.AppendLine("            }");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            sb.AppendLine("                await hookAction();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Runs all tests.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"args\">The command line arguments.</param>");
            sb.AppendLine("        public static async global::System.Threading.Tasks.Task RunAllAsync(string[]? args = null)");
            sb.AppendLine("        {");
            sb.AppendLine("            // Initialize Coverage");
            sb.AppendLine("            InitializeCoverage();");
            sb.AppendLine();
            sb.AppendLine("            // Initialize Dependencies");
            // Register Class Fixtures automatically if not already registered
            var allFixtures = methods.Where(m => m != null).SelectMany(m => m!.FixtureTypes).Distinct().ToList();
            foreach (var fixture in allFixtures)
            {
                sb.AppendLine($"            try {{ Services.AddSingleton<{fixture}>(() => new {fixture}()); }} catch {{ }} // Auto-register fixture");
            }

            // Register Executors automatically
            foreach (var exec in executors)
            {
                sb.AppendLine($"            try {{ Services.AddTransient<{exec}>(() => new {exec}()); }} catch {{ }} // Auto-register executor");
            }

            foreach (var configMethod in configMethods)
            {
                if (!string.IsNullOrEmpty(configMethod))
                {
                    sb.AppendLine($"            {configMethod}(Services);");
                }
            }

            // Initialize Class Fixtures that implement IAsyncLifetime
            foreach (var fixture in allFixtures)
            {
                sb.AppendLine($"            try {{ var inst_{fixture.Replace(".", "_")} = Services.GetService(typeof({fixture})); if (inst_{fixture.Replace(".", "_")} is IAsyncLifetime al_init_{fixture.Replace(".", "_")}) await al_init_{fixture.Replace(".", "_")}.InitializeAsync(); }} catch {{ }}");
            }

            // Initialize Session Context
            sb.AppendLine("            var sessionContext = new Prova.TestContext(\"Session\", new global::System.Collections.Generic.Dictionary<string, string>(), global::System.Threading.CancellationToken.None);");
            sb.AppendLine("            Prova.TestContext.Current = sessionContext;");

            foreach (var hook in beforeAssembly)
            {
                if (string.IsNullOrEmpty(hook.Method)) continue;
                string executorType = hook.ExecutorType != null ? $"typeof({hook.ExecutorType})" : "null";
                string hookAction = hook.IsAsync ? $"async () => await {hook.Method}()" : $"() => {{ {hook.Method}(); return global::System.Threading.Tasks.Task.CompletedTask; }}";
                sb.AppendLine($"            await TestRunnerExecutor.InvokeHookHelper({hookAction}, \"{hook.Method}\", {executorType});");
            }

            sb.AppendLine("            try {");
            sb.AppendLine("                args ??= global::System.Array.Empty<string>();");
            sb.AppendLine("                bool hasCoverage = args.Any(a => a == \"--coverage\");");
            sb.AppendLine("                var filteredArgs = args.Where(a => a != \"--coverage\").ToArray();");
            sb.AppendLine("                bool isMtp = args.Any(a => a == \"--list-tests\" || a == \"--server\" || a.StartsWith(\"--client-port\") || a == \"--report-trx\" || hasCoverage || a == \"--help\" || a == \"-?\" || a == \"-h\" || a == \"--crashdump\" || a == \"--hangdump\" || a.StartsWith(\"--hangdump-timeout\"));");
            sb.AppendLine();
            sb.AppendLine("                if (isMtp)");
            sb.AppendLine("                {");
            sb.AppendLine("                    await RunMtpAsync(filteredArgs, hasCoverage);");
            sb.AppendLine("                }");
            sb.AppendLine("                else");
            sb.AppendLine("                {");
            sb.AppendLine("                    await RunSimpleAsync(filteredArgs, hasCoverage);");
            sb.AppendLine("                }");
            sb.AppendLine("            } finally {");
                // Dispose Class Fixtures
                foreach (var fixture in allFixtures)
                {
                    sb.AppendLine($"                try {{ var inst_{fixture.Replace(".", "_")} = Services.GetService(typeof({fixture})); if (inst_{fixture.Replace(".", "_")} is IAsyncLifetime al_disp_{fixture.Replace(".", "_")}) await al_disp_{fixture.Replace(".", "_")}.DisposeAsync(); else if (inst_{fixture.Replace(".", "_")} is global::System.IDisposable d_disp_{fixture.Replace(".", "_")}) d_disp_{fixture.Replace(".", "_")}.Dispose(); }} catch {{ }}");
                }

                foreach (var hook in afterAssembly)
                {
                    if (string.IsNullOrEmpty(hook.Method)) continue;
                    string executorType = hook.ExecutorType != null ? $"typeof({hook.ExecutorType})" : "null";
                    string hookAction = hook.IsAsync ? $"async () => await {hook.Method}()" : $"() => {{ {hook.Method}(); return global::System.Threading.Tasks.Task.CompletedTask; }}";
                    sb.AppendLine($"                try {{ await TestRunnerExecutor.InvokeHookHelper({hookAction}, \"{hook.Method}\", {executorType}); }} catch {{ }}");
                }
                
                sb.AppendLine("                var sessionOutput = sessionContext.Output.Output;");
                sb.AppendLine("                if (!string.IsNullOrEmpty(sessionOutput))");
                sb.AppendLine("                {");
                sb.AppendLine("                    global::System.Console.WriteLine(\"Session Output:\");");
                sb.AppendLine("                    global::System.Console.WriteLine(sessionOutput);");
                sb.AppendLine("                }");

                sb.AppendLine("                Prova.TestContext.Current = null!;");
                sb.AppendLine("                Services.Dispose();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async global::System.Threading.Tasks.Task RunMtpAsync(string[] args, bool hasCoverage)");
            sb.AppendLine("        {");
            sb.AppendLine("            var builder = await global::Microsoft.Testing.Platform.Builder.TestApplication.CreateBuilderAsync(args);");
            sb.AppendLine("            builder.AddCrashDumpProvider();");
            sb.AppendLine("            builder.AddHangDumpProvider();");
            sb.AppendLine("            builder.RegisterTestFramework(");
            sb.AppendLine("                _ => new ProvaCapabilities(),");
            sb.AppendLine("                (cap, _) => new HybridMtpAdapter(GetTests(), cap));");
            sb.AppendLine("            using var app = await builder.BuildAsync();");
            sb.AppendLine("            await app.RunAsync();");
            sb.AppendLine();
            sb.AppendLine("            if (hasCoverage)");
            sb.AppendLine("            {");
            sb.AppendLine("                CoverageRegistry.EmitLcov(\"coverage.lcov\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static async global::System.Threading.Tasks.Task RunSimpleAsync(string[] args, bool hasCoverage)");
            sb.AppendLine("        {");
            sb.AppendLine("            var reporter = new ConsoleReporter();");
            sb.AppendLine("            int passed = 0, failed = 0, skipped = 0;");
            sb.AppendLine("            var sw = global::System.Diagnostics.Stopwatch.StartNew();");
            sb.AppendLine();
            sb.AppendLine("            var activeTests = GetTests().ToList();");
            sb.AppendLine("            var config = global::Prova.Configuration.ConfigLoader.Load();");
            sb.AppendLine();
            sb.AppendLine("            foreach (var test in activeTests)");
            sb.AppendLine("            {");
            sb.AppendLine("                foreach (var prop in config.GlobalProperties)");
            sb.AppendLine("                {");
            sb.AppendLine("                    if (!test.Properties.ContainsKey(prop.Key)) test.Properties[prop.Key] = prop.Value;");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            ");
            sb.AppendLine("            // CLI Filtering logic");
            sb.AppendLine("            var filterArgs = args.Where(a => a.StartsWith(\"--filter=\")).Select(a => a.Substring(\"--filter=\".Length)).ToList();");
            sb.AppendLine("            var treeNodeFilters = args.Where(a => a.StartsWith(\"--treenode-filter=\")).Select(a => a.Substring(\"--treenode-filter=\".Length)).ToList();");
            sb.AppendLine("            var keywordFilters = args.Where(a => !a.StartsWith(\"-\")).ToList();");
            sb.AppendLine();
            sb.AppendLine("            if (filterArgs.Any())");
            sb.AppendLine("            {");
            sb.AppendLine("                activeTests = activeTests.Where(t => ");
            sb.AppendLine("                {");
            sb.AppendLine("                    return filterArgs.All(f => ");
            sb.AppendLine("                    {");
            sb.AppendLine("                        var parts = f.Split('=');");
            sb.AppendLine("                        if (parts.Length == 2)");
            sb.AppendLine("                        {");
            sb.AppendLine("                            return t.Properties.TryGetValue(parts[0], out var val) && val == parts[1];");
            sb.AppendLine("                        }");
            sb.AppendLine("                        return t.Properties.ContainsKey(f) || t.Properties.Values.Contains(f);");
            sb.AppendLine("                    });");
            sb.AppendLine("                }).ToList();");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            if (treeNodeFilters.Any())");
            sb.AppendLine("            {");
            sb.AppendLine("                activeTests = activeTests.Where(t => treeNodeFilters.Any(f => ");
            sb.AppendLine("                {");
            sb.AppendLine("                    if (string.IsNullOrEmpty(t.FullName)) return false;");
            sb.AppendLine("                    if (f.EndsWith(\"*\")) return t.FullName.StartsWith(f.Substring(0, f.Length - 1), global::System.StringComparison.OrdinalIgnoreCase);");
            sb.AppendLine("                    return t.FullName.Equals(f, global::System.StringComparison.OrdinalIgnoreCase);");
            sb.AppendLine("                })).ToList();");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            if (keywordFilters.Any())");
            sb.AppendLine("            {");
            sb.AppendLine("                activeTests = activeTests.Where(t => keywordFilters.Any(f => ");
            sb.AppendLine("                    t.DisplayName.Contains(f, global::System.StringComparison.OrdinalIgnoreCase) || ");
            sb.AppendLine("                    (t.FullName != null && t.FullName.Contains(f, global::System.StringComparison.OrdinalIgnoreCase)) ||");
            sb.AppendLine("                    t.Properties.Values.Any(v => v.Contains(f, global::System.StringComparison.OrdinalIgnoreCase)))).ToList();");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            var tasks = new List<global::System.Threading.Tasks.Task>();");
            string maxConcurrencyExpr = globalMaxParallel.HasValue 
                ? (globalMaxParallel.Value == -1 ? "1000" : globalMaxParallel.Value.ToString(global::System.Globalization.CultureInfo.InvariantCulture)) 
                : "global::System.Environment.ProcessorCount";

            sb.AppendLine($"            int maxConcurrency = config.MaxParallel ?? {maxConcurrencyExpr};");
            sb.AppendLine("            var globalSemaphore = new SemaphoreSlim(maxConcurrency);");
            sb.AppendLine("            var exclusiveLock = new SemaphoreSlim(1, 1);");
            sb.AppendLine("            var classSemaphores = new ConcurrentDictionary<string, SemaphoreSlim>();");
            sb.AppendLine("            var initializedClasses = new ConcurrentDictionary<string, bool>();");
            sb.AppendLine("            var classCounts = new ConcurrentDictionary<string, int>();");
            sb.AppendLine("            var resourceSemaphores = new ConcurrentDictionary<string, SemaphoreSlim>();");
            sb.AppendLine();
            sb.AppendLine("            // Initialize Class Semaphores based on MaxParallel");
            sb.AppendLine("            foreach (var test in activeTests.Where(t => t.MaxParallel.HasValue && !string.IsNullOrEmpty(t.ClassName)))");
            sb.AppendLine("            {");
            sb.AppendLine("                classSemaphores.GetOrAdd(test.ClassName!, _ => new SemaphoreSlim(test.MaxParallel.Value, test.MaxParallel.Value));");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            // Initialize Class Counts");
            sb.AppendLine("            foreach (var test in activeTests)");
            sb.AppendLine("            {");
            sb.AppendLine("                classCounts.AddOrUpdate(test.ClassName ?? \"\", 1, (k, v) => v + 1);");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            foreach (var test in activeTests)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (test.SkipReason != null)");
            sb.AppendLine("                {");
            sb.AppendLine("                    await EventRegistry.DispatchEndAsync(test, TestResult.Skipped, 0);");
            sb.AppendLine("                    reporter.OnTestSkipped(test.DisplayName, test.SkipReason);");
            sb.AppendLine("                    global::System.Threading.Interlocked.Increment(ref skipped);");
            sb.AppendLine("                    continue;");
            sb.AppendLine("                }");
            sb.AppendLine();
            sb.AppendLine("                // Filtering moved up to initialization");
            sb.AppendLine();
            sb.AppendLine("                tasks.Add(global::System.Threading.Tasks.Task.Run(async () => {");
            sb.AppendLine("                    bool hasGlobalSlot = false;");
            sb.AppendLine("                    bool hasClassSlot = false;");
            sb.AppendLine("                    bool hasExclusiveLock = false;");
            sb.AppendLine("                    var heldResources = new List<SemaphoreSlim>();");
            sb.AppendLine();
            sb.AppendLine("                    try {");
            sb.AppendLine("                        // 1. Wait for Exclusive Lock (for isolation)");
            sb.AppendLine("                        if (test.DoNotParallelize)");
            sb.AppendLine("                        {");
            sb.AppendLine("                            await exclusiveLock.WaitAsync();");
            sb.AppendLine("                            hasExclusiveLock = true;");
            sb.AppendLine("                            // For DoNotParallelize, we wait for ALL global slots to be free");
            sb.AppendLine("                            for (int i = 0; i < maxConcurrency; i++) await globalSemaphore.WaitAsync();");
            sb.AppendLine("                            hasGlobalSlot = true; // Technically has ALL slots");
            sb.AppendLine("                        }");
            sb.AppendLine("                        else");
            sb.AppendLine("                        {");
            sb.AppendLine("                            // Normal test: Wait for one global slot");
            sb.AppendLine("                            await globalSemaphore.WaitAsync();");
            sb.AppendLine("                            hasGlobalSlot = true;");
            sb.AppendLine("                        }");
            sb.AppendLine();
            sb.AppendLine("                        // 2. Wait for Class Semaphore (if defined)");
            sb.AppendLine("                        string className = test.ClassName ?? \"\";");
            sb.AppendLine("                        if (classSemaphores.TryGetValue(className, out var classSem))");
            sb.AppendLine("                        {");
            sb.AppendLine("                            await classSem.WaitAsync();");
            sb.AppendLine("                            hasClassSlot = true;");
            sb.AppendLine("                        }");
            sb.AppendLine();
            sb.AppendLine("                        // 2.1 Resource Constraints");
            sb.AppendLine("                        if (test.ResourceConstraints != null && test.ResourceConstraints.Count > 0 && !test.DoNotParallelize)");
            sb.AppendLine("                        {");
            sb.AppendLine("                            var sortedResources = test.ResourceConstraints.Where(x => x != null).OrderBy(x => x!).ToArray();");
            sb.AppendLine("                            foreach (var res in sortedResources)");
            sb.AppendLine("                            {");
            sb.AppendLine("                                var sem = resourceSemaphores.GetOrAdd(res!, _ => new SemaphoreSlim(1, 1));");
            sb.AppendLine("                                await sem.WaitAsync();");
            sb.AppendLine("                                heldResources.Add(sem);");
            sb.AppendLine("                            }");
            sb.AppendLine("                        }");
            sb.AppendLine();
            sb.AppendLine("                        // 2.2 Parallel Limiters");
            sb.AppendLine("                        if (test.ParallelLimiters != null && test.ParallelLimiters.Count > 0 && !test.DoNotParallelize)");
            sb.AppendLine("                        {");
            sb.AppendLine("                             var sortedLimiters = test.ParallelLimiters.OrderBy(x => x.Key).ToArray();");
            sb.AppendLine("                             foreach (var (key, limit) in sortedLimiters)");
            sb.AppendLine("                             {");
            sb.AppendLine("                                 var sem = resourceSemaphores.GetOrAdd(key!, _ => new SemaphoreSlim(limit, limit));");
            sb.AppendLine("                                 await sem.WaitAsync();");
            sb.AppendLine("                                 heldResources.Add(sem);");
            sb.AppendLine("                             }");
            sb.AppendLine("                        }");
            sb.AppendLine();
            sb.AppendLine("                        // 3. Class Initialize");
            sb.AppendLine("                        if (initializedClasses.TryAdd(className, true))");
            sb.AppendLine("                        {");
            sb.AppendLine("                             foreach(var hook in _beforeEveryClass) try { await hook(); } catch { }");
            sb.AppendLine("                             if (test.ClassFixtures != null)");
            sb.AppendLine("                             {");
            sb.AppendLine("                                 foreach(var hook in test.ClassFixtures) await hook();");
            sb.AppendLine("                             }");
            sb.AppendLine("                             if (test.ClassBefore != null)");
            sb.AppendLine("                             {");
            sb.AppendLine("                                 foreach(var hook in test.ClassBefore) await hook();");
            sb.AppendLine("                             }");
            sb.AppendLine("                        }");
            sb.AppendLine();
            sb.AppendLine("                        // 4. Global Before Every Test Hooks");
            sb.AppendLine("                        foreach(var hook in _beforeEveryTest) try { await hook(); } catch { }");
            sb.AppendLine();
            sb.AppendLine("                        var effectiveRetry = test.RetryCount ?? config.DefaultRetryCount ?? 0;");
            sb.AppendLine("                        var effectiveRepeat = test.Repeat ?? 1;");
            sb.AppendLine("                        var effectiveTimeout = test.Timeout ?? config.DefaultTimeoutMs;");
            sb.AppendLine("                        var effectiveCulture = test.Culture ?? config.DefaultCulture;");
            sb.AppendLine();
            sb.AppendLine("                        // 5. Run Test");
            sb.AppendLine("                        if (await RunTestSafe(test, reporter, effectiveRetry, effectiveRepeat, effectiveTimeout, effectiveCulture))");
            sb.AppendLine("                            global::System.Threading.Interlocked.Increment(ref passed);");
            sb.AppendLine("                        else");
            sb.AppendLine("                            global::System.Threading.Interlocked.Increment(ref failed);");
            sb.AppendLine();
            sb.AppendLine("                        // 6. Global After Every Test Hooks");
            sb.AppendLine("                        foreach(var hook in _afterEveryTest) try { await hook(); } catch { }");
            sb.AppendLine();
            sb.AppendLine("                    } finally {");
            sb.AppendLine("                        // 5. Cleanup & Release");
            sb.AppendLine("                        string className = test.ClassName ?? \"\";");
            sb.AppendLine("                        if (classCounts.AddOrUpdate(className, 0, (k, v) => v - 1) == 0)");
            sb.AppendLine("                        {");
            sb.AppendLine("                            if (test.ClassAfter != null)");
            sb.AppendLine("                            {");
            sb.AppendLine("                                foreach(var hook in test.ClassAfter) try { await hook(); } catch { }");
            sb.AppendLine("                            }");
            sb.AppendLine("                            foreach(var hook in _afterEveryClass) try { await hook(); } catch { }");
            sb.AppendLine("                        }");
            sb.AppendLine();
            sb.AppendLine("                        if (hasClassSlot) classSemaphores[className].Release();");
            sb.AppendLine("                        foreach(var sem in heldResources) sem.Release();");
            sb.AppendLine("                        ");
            sb.AppendLine("                        if (test.DoNotParallelize)");
            sb.AppendLine("                        {");
            sb.AppendLine("                            if (hasGlobalSlot) for (int i = 0; i < maxConcurrency; i++) globalSemaphore.Release();");
            sb.AppendLine("                            if (hasExclusiveLock) exclusiveLock.Release();");
            sb.AppendLine("                        }");
            sb.AppendLine("                        else");
            sb.AppendLine("                        {");
            sb.AppendLine("                            if (hasGlobalSlot) globalSemaphore.Release();");
            sb.AppendLine("                        }");
            sb.AppendLine("                    }");
            sb.AppendLine("                }));");
            sb.AppendLine("            }");
            sb.AppendLine("            await global::System.Threading.Tasks.Task.WhenAll(tasks);");
            sb.AppendLine();
            sb.AppendLine("            sw.Stop();");
            sb.AppendLine("            reporter.OnComplete(passed, failed, skipped, sw.Elapsed);");
            sb.AppendLine();
            sb.AppendLine("            // Coverage Report Emission");
            sb.AppendLine("            if (hasCoverage)");
            sb.AppendLine("            {");
            sb.AppendLine("                CoverageRegistry.EmitLcov(\"coverage.lcov\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Gets the list of available tests.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static global::System.Collections.Generic.IEnumerable<ProvaTest> GetTests()");
            sb.AppendLine("        {");
            sb.AppendLine("            var list = new global::System.Collections.Generic.List<ProvaTest>();");

            int probeCounter = 0;
            var coverageMetadata = new List<string>();

            var allMethods = methods.Where(m => m != null).ToList();
            var groupedMethods = allMethods.GroupBy(m => m!.ClassName);

            foreach (var group in groupedMethods)
            {
                var className = group.Key;
                sb.AppendLine($"            // Class: {className}");

                foreach (var method in group)
                {
                    if (method == null) continue;

                    var classFixtures = method.FixtureTypes.ToList();

                    // Generic Variant Expansion
                    var cVariants = method.ClassVariants.Count > 0 ? method.ClassVariants : new List<string[]> { Array.Empty<string>() };
                    var mVariants = method.MethodVariants.Count > 0 ? method.MethodVariants : new List<string[]> { Array.Empty<string>() };
                    var namedVariants = new global::System.Collections.Generic.List<string?>();
                    if (method.NamedVariants != null && method.NamedVariants.Count > 0)
                        namedVariants.AddRange(method.NamedVariants);
                    else
                        namedVariants.Add(null);

                    foreach (var cv in cVariants)
                    {
                        foreach (var mv in mVariants)
                        {
                            foreach (var variantName in namedVariants)
                            {
                            string concreteClassName = cv.Length > 0 ? $"{RemoveGenerics(method.ClassName)}<{string.Join(", ", cv)}>" : method.ClassName;
                            string concreteMethodName = mv.Length > 0 ? $"{method.MethodName}<{string.Join(", ", mv)}>" : method.MethodName;
                            
                            string variantSuffix = "";
                            if (cv.Length > 0) variantSuffix += $"<{string.Join(", ", cv)}>";
                            if (mv.Length > 0) variantSuffix += (variantSuffix.Length > 0 ? "." : "") + $"{method.MethodName}<{string.Join(", ", mv)}>";
                            if (variantName != null) variantSuffix += $" [Variant: {variantName}]";
                            if (variantSuffix.Length > 0 && variantName == null) variantSuffix = " [" + variantSuffix + "]";

                            // Generate Class-Level Data Loops if present
                            bool hasClassData = method.ClassTestData.Count > 0 || method.ClassMemberData.Count > 0 || method.ClassClassData.Count > 0 || method.ClassClassDataSources.Count > 0 || method.ClassMethodDataSources.Count > 0 || method.ClassCustomDataGenerators.Count > 0 || method.ClassDIDataSources.Count > 0;
                            if (hasClassData)
                            {
                                if (method.ClassTestData.Count > 0)
                                {
                                    foreach (var classRow in method.ClassTestData)
                                    {
                                        string classRowStr = string.Join(", ", classRow);
                                        EmitMethodExecution(sb, method, concreteClassName, concreteMethodName, variantSuffix, classRowStr, $"(ClassData_{probeCounter})", classFixtures, ref probeCounter, coverageMetadata, cv, mv, variantName);
                                    }
                                }

                                if (method.ClassMemberData.Count > 0)
                                {
                                    foreach (var md in method.ClassMemberData)
                                    {
                                        sb.AppendLine($"            // ClassMemberData: {md.MemberName}");
                                        string sourceExpr = md.MemberType != null ? md.MemberType + "." + md.MemberName : concreteClassName + "." + md.MemberName;
                                        if (md.IsMethod) sourceExpr += "(" + string.Join(", ", md.Parameters) + ")";

                                        sb.AppendLine($"            foreach (var classDataRow in (global::System.Collections.Generic.IEnumerable<object[]>)({sourceExpr}))");
                                        sb.AppendLine("            {");
                                        sb.AppendLine("                if (classDataRow != null)");
                                        sb.AppendLine("                {");
                                        EmitMethodExecution(sb, method, concreteClassName, concreteMethodName, variantSuffix, "classDataRow", "(Class:{string.Join(\", \", classDataRow)})", classFixtures, ref probeCounter, coverageMetadata, cv, mv, variantName, isClassDataRow: true);
                                        sb.AppendLine("                }");
                                        sb.AppendLine("            }");
                                    }
                                }

                                if (method.ClassClassData.Count > 0)
                                {
                                    foreach (var cdType in method.ClassClassData)
                                    {
                                        sb.AppendLine($"            // ClassClassData: {cdType}");
                                        sb.AppendLine($"            foreach (var classDataRow in (global::System.Collections.Generic.IEnumerable<object[]>)new {cdType}())");
                                        sb.AppendLine("            {");
                                        sb.AppendLine("                if (classDataRow != null)");
                                        sb.AppendLine("                {");
                                        EmitMethodExecution(sb, method, concreteClassName, concreteMethodName, variantSuffix, "classDataRow", "(Class:{string.Join(\", \", classDataRow)})", classFixtures, ref probeCounter, coverageMetadata, cv, mv, variantName, isClassDataRow: true);
                                        sb.AppendLine("                }");
                                        sb.AppendLine("            }");
                                    }
                                }

                                if (method.ClassClassDataSources.Count > 0)
                                {
                                    foreach (var cdType in method.ClassClassDataSources)
                                    {
                                        sb.AppendLine($"            // ClassClassDataSource: {cdType}");
                                        sb.AppendLine($"            foreach (var classDataRow in (global::System.Collections.Generic.IEnumerable<object[]>)TestRunnerExecutor.Services.Get<{cdType}>())");
                                        sb.AppendLine("            {");
                                        sb.AppendLine("                if (classDataRow != null)");
                                        sb.AppendLine("                {");
                                        EmitMethodExecution(sb, method, concreteClassName, concreteMethodName, variantSuffix, "classDataRow", "(Class:{string.Join(\", \", classDataRow)})", classFixtures, ref probeCounter, coverageMetadata, cv, mv, variantName, isClassDataRow: true);
                                        sb.AppendLine("                }");
                                        sb.AppendLine("            }");
                                    }
                                }

                                if (method.ClassMethodDataSources.Count > 0)
                                {
                                    foreach (var md in method.ClassMethodDataSources)
                                    {
                                        sb.AppendLine($"            // ClassMethodDataSource: {md.MemberName}");
                                        string sourceExpr = md.MemberType != null ? $"TestRunnerExecutor.Services.Get<{md.MemberType}>().{md.MemberName}" : $"TestRunnerExecutor.Services.Get<{concreteClassName}>().{md.MemberName}";
                                        if (md.IsMethod) sourceExpr += "(" + string.Join(", ", md.Parameters) + ")";

                                        sb.AppendLine($"            foreach (var classDataRow in (global::System.Collections.Generic.IEnumerable<object[]>)({sourceExpr}))");
                                        sb.AppendLine("            {");
                                        sb.AppendLine("                if (classDataRow != null)");
                                        sb.AppendLine("                {");
                                        EmitMethodExecution(sb, method, concreteClassName, concreteMethodName, variantSuffix, "classDataRow", "(Class:{string.Join(\", \", classDataRow)})", classFixtures, ref probeCounter, coverageMetadata, cv, mv, variantName, isClassDataRow: true);
                                        sb.AppendLine("                }");
                                        sb.AppendLine("            }");
                                    }
                                }

                                if (method.ClassDIDataSources.Count > 0)
                                {
                                    foreach (var md in method.ClassDIDataSources)
                                    {
                                        sb.AppendLine($"            // ClassDIDataSource: {md.MemberType}");
                                        string sourceExpr = string.IsNullOrEmpty(md.MemberName) ? $"TestRunnerExecutor.Services.Get<{md.MemberType}>()" : $"TestRunnerExecutor.Services.Get<{md.MemberType}>().{md.MemberName}";
                                        if (md.IsMethod) sourceExpr += "()";

                                        sb.AppendLine($"            foreach (var classDataRow in (global::System.Collections.Generic.IEnumerable<object[]>)({sourceExpr}))");
                                        sb.AppendLine("            {");
                                        sb.AppendLine("                if (classDataRow != null)");
                                        sb.AppendLine("                {");
                                        EmitMethodExecution(sb, method, concreteClassName, concreteMethodName, variantSuffix, "classDataRow", "(Class:{string.Join(\", \", classDataRow)})", classFixtures, ref probeCounter, coverageMetadata, cv, mv, variantName, isClassDataRow: true);
                                        sb.AppendLine("                }");
                                        sb.AppendLine("            }");
                                    }
                                }

                                if (method.ClassCustomDataGenerators.Count > 0)
                                {
                                    foreach (var gen in method.ClassCustomDataGenerators)
                                    {
                                        sb.AppendLine($"            // ClassCustomDataGenerator: {gen.AttributeType}");
                                        string initArgs = string.Join(", ", gen.Arguments);
                                        sb.AppendLine($"            foreach (var classDataRow in ((DataSourceGeneratorAttribute)new {gen.AttributeType}({initArgs})).GetData())");
                                        sb.AppendLine("            {");
                                        sb.AppendLine("                if (classDataRow != null)");
                                        sb.AppendLine("                {");
                                        EmitMethodExecution(sb, method, concreteClassName, concreteMethodName, variantSuffix, "classDataRow", "(Class:{string.Join(\", \", classDataRow)})", classFixtures, ref probeCounter, coverageMetadata, cv, mv, variantName, isClassDataRow: true);
                                        sb.AppendLine("                }");
                                        sb.AppendLine("            }");
                                    }
                                }
                            }
                            else
                            {
                                // No class data, just normal method execution (possibly with method theories)
                                EmitMethodExecution(sb, method, concreteClassName, concreteMethodName, variantSuffix, null, "", classFixtures, ref probeCounter, coverageMetadata, cv, mv, variantName);
                            }
                            }
                        }
                    }
                }
            }
            
            if (factories != null && factories.Count > 0)
            {
                sb.AppendLine("            var builder = new Prova.DynamicTestBuilder();");
                foreach (var factory in factories.Where(f => !string.IsNullOrEmpty(f)))
                {
                    sb.AppendLine($"            {factory}(builder);");
                }
                sb.AppendLine("            list.AddRange(builder.Tests);");
            }

            sb.AppendLine("            return list;");
            sb.AppendLine("        }");
            sb.AppendLine();
            GenerateInitializeCoverage(sb, coverageMetadata);
            sb.AppendLine();
            sb.AppendLine("        private static async global::System.Threading.Tasks.Task<bool> RunTestSafe(ProvaTest testInfo, ITestReporter reporter, int retryCount = 0, int repeatCount = 1, int? timeout = null, string? culture = null)");
            sb.AppendLine("        {");
            sb.AppendLine("             var sw = global::System.Diagnostics.Stopwatch.StartNew();");
            sb.AppendLine("             await EventRegistry.DispatchStartAsync(testInfo);");
            sb.AppendLine("             var test = testInfo.ExecuteDelegate;");
            sb.AppendLine("             var name = testInfo.DisplayName;");
            sb.AppendLine("             var properties = testInfo.Properties;");
            sb.AppendLine("             var description = testInfo.Description;");
            sb.AppendLine("             reporter.OnTestStarting(name, description);");
             sb.AppendLine("             string lastOutput = \"\";");
             sb.AppendLine("             string stdOut = \"\";"); // Captured output
            sb.AppendLine();
            sb.AppendLine("             // Culture Switching");
            sb.AppendLine("             global::System.Globalization.CultureInfo? originalCulture = null;");
            sb.AppendLine("             global::System.Globalization.CultureInfo? originalUICulture = null;");
            sb.AppendLine();
            sb.AppendLine("             if (culture != null)");
            sb.AppendLine("             {");
            sb.AppendLine("                 try {");
            sb.AppendLine("                     var newCulture = global::System.Globalization.CultureInfo.GetCultureInfo(culture);");
            sb.AppendLine("                     originalCulture = global::System.Globalization.CultureInfo.CurrentCulture;");
            sb.AppendLine("                     originalUICulture = global::System.Globalization.CultureInfo.CurrentUICulture;");
            sb.AppendLine("                     global::System.Globalization.CultureInfo.CurrentCulture = newCulture;");
            sb.AppendLine("                     global::System.Globalization.CultureInfo.CurrentUICulture = newCulture;");
            sb.AppendLine("                 } catch { } ");
            sb.AppendLine("             }");
            sb.AppendLine();
            sb.AppendLine("             try");
            sb.AppendLine("             {");
            sb.AppendLine("                 for (int i = 0; i < repeatCount; i++)");
            sb.AppendLine("                 {");
            sb.AppendLine("                     int attempt = 0;");
            sb.AppendLine("                         while (true)");
            sb.AppendLine("                         {");
            sb.AppendLine("                             using var cts = new global::System.Threading.CancellationTokenSource();");
            sb.AppendLine("                             if (timeout.HasValue) cts.CancelAfter(timeout.Value);");
            sb.AppendLine();
            sb.AppendLine("                             var context = new Prova.TestContext(name, properties, cts.Token, testInfo.Variant);");
            sb.AppendLine("                             var previousContext = Prova.TestContext.Current;");
            sb.AppendLine("                             Prova.TestContext.Current = context;");
            sb.AppendLine();
            sb.AppendLine("                             try {");
            sb.AppendLine("                                 var executor = GetExecutorHelper<ITestExecutor>(testInfo.ExecutorType);");
            sb.AppendLine("                                 if (timeout.HasValue && timeout.Value > 0)");
            sb.AppendLine("                                 {");
            sb.AppendLine("                                     global::System.Func<global::System.Threading.Tasks.Task<string?>> action = test;");
            sb.AppendLine("                                     if (executor != null) action = () => executor.ExecuteAsync(test, testInfo);");
            sb.AppendLine();
            sb.AppendLine("                                     var t = global::System.Threading.Tasks.Task.Run(action, cts.Token);");
            sb.AppendLine("                                     var timeoutTask = global::System.Threading.Tasks.Task.Delay(timeout.Value, cts.Token);");
            sb.AppendLine("                                     var completedTask = await global::System.Threading.Tasks.Task.WhenAny(t, timeoutTask);");
            sb.AppendLine("                                     if (completedTask == t || t.IsCompleted)");
            sb.AppendLine("                                         lastOutput = await t ?? \"\";");
            sb.AppendLine("                                     else");
            sb.AppendLine("                                         throw new global::System.TimeoutException($\"Test exceeded timeout of {timeout.Value}ms\");");
            sb.AppendLine("                                 }");
            sb.AppendLine("                                 else");
            sb.AppendLine("                                 {");
            sb.AppendLine("                                     if (executor != null)");
            sb.AppendLine("                                         lastOutput = await executor.ExecuteAsync(test, testInfo) ?? \"\";");
            sb.AppendLine("                                     else");
            sb.AppendLine("                                         lastOutput = await test() ?? \"\";");
            sb.AppendLine("                                 }");
            sb.AppendLine("                                 stdOut = context.Output.Output ?? \"\";");
            sb.AppendLine("                                 break; // Success for this repetition");
            sb.AppendLine("                             } catch (global::System.Exception ex) {");
            sb.AppendLine("                                 stdOut = context.Output.Output ?? \"\";");
            sb.AppendLine("                                 if (attempt < retryCount) {");
            sb.AppendLine("                                     attempt++;");
            sb.AppendLine("                                     continue; // Retry this repetition");
            sb.AppendLine("                                 }");
            sb.AppendLine("                                 sw.Stop();");
            sb.AppendLine("                                 reporter.OnTestFailure(name, ex, stdOut); ");
            sb.AppendLine("                                 await EventRegistry.DispatchEndAsync(testInfo, TestResult.Failed, sw.ElapsedMilliseconds);");
            sb.AppendLine("                                 return false;");
            sb.AppendLine("                             } finally {");
            sb.AppendLine("                                 Prova.TestContext.Current = previousContext;");
            sb.AppendLine("                             }");
            sb.AppendLine("                         }");
            sb.AppendLine("                 }");
            sb.AppendLine("                 sw.Stop();");
            sb.AppendLine("                 var finalOutput = (string.IsNullOrEmpty(lastOutput) ? \"\" : lastOutput + System.Environment.NewLine) + stdOut;");
            sb.AppendLine("                 reporter.OnTestSuccess(name, finalOutput);");
            sb.AppendLine("                 await EventRegistry.DispatchEndAsync(testInfo, TestResult.Passed, sw.ElapsedMilliseconds);");
            sb.AppendLine("                 return true;");
            sb.AppendLine("             }");
            sb.AppendLine("             catch (global::System.Exception ex)");
            sb.AppendLine("             {");
            sb.AppendLine("                 sw.Stop();");
            sb.AppendLine("                 reporter.OnTestFailure(name, ex, stdOut); ");
            sb.AppendLine("                 await EventRegistry.DispatchEndAsync(testInfo, TestResult.Failed, sw.ElapsedMilliseconds);");
            sb.AppendLine("                 return false;");
            sb.AppendLine("             }");
            sb.AppendLine("             finally");
            sb.AppendLine("             {");
            sb.AppendLine("                 if (originalCulture != null)");
            sb.AppendLine("                 {");
            sb.AppendLine("                     global::System.Globalization.CultureInfo.CurrentCulture = originalCulture;");
            sb.AppendLine("                     global::System.Globalization.CultureInfo.CurrentUICulture = originalUICulture;");
            sb.AppendLine("                 }");
            sb.AppendLine("             }");
            sb.AppendLine("        }");


            sb.AppendLine("    }");

            sb.AppendLine("}");

            context.AddSource("TestRunnerExecutor.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static void GenerateInitializeCoverage(StringBuilder sb, List<string> metadata)
        {
            sb.AppendLine("        private static void InitializeCoverage()");
            sb.AppendLine("        {");
            sb.AppendLine($"            var metadata = new string[{metadata.Count}] {{");
            foreach (var m in metadata) sb.AppendLine($"                \"{m.Replace("\"", "\\\"")}\",");
            sb.AppendLine("            };");
            sb.AppendLine($"            CoverageRegistry.Initialize({metadata.Count}, metadata);");
            sb.AppendLine("        }");
        }

        private static void EmitMethodExecution(StringBuilder sb, TestMethodModel method, string concreteClassName, string concreteMethodName, string variantSuffix, string? classRowStr, string classSuffix, List<string> classFixtures, ref int probeCounter, List<string> coverageMetadata, string[] cv, string[] mv, string? variantName, bool isClassDataRow = false)
        {
            if (method.CombinatorialValues != null && method.CombinatorialValues.Count > 0)
            {
                // Combinatorial Execution (Matrix)
                var paramVars = new List<string>();
                var indent = "            ";
                
                // Nest loops
                for (int i = 0; i < method.CombinatorialValues.Count; i++)
                {
                    var (paramName, values) = method.CombinatorialValues[i];
                    var valArray = "new [] { " + string.Join(", ", values) + " }";
                    var loopVar = $"p{i}_{paramName}";
                    paramVars.Add(loopVar);

                    sb.AppendLine($"{indent}foreach (var {loopVar} in {valArray})");
                    sb.AppendLine($"{indent}{{");
                    indent += "    ";
                }

                // Inner Body
                int probeId = probeCounter++;
                var args = string.Join(", ", paramVars);

                var formattingArgsList = new List<string>();
                for (int i = 0; i < method.CombinatorialValues.Count; i++)
                {
                    string? fmt = method.ParameterFormatters.Count > i ? method.ParameterFormatters[i] : null;
                    if (fmt != null)
                        formattingArgsList.Add($"new {fmt}().Format({paramVars[i]})");
                    else
                        formattingArgsList.Add(paramVars[i]);
                }
                var formattingArgs = string.Join(", ", formattingArgsList);

                var displayArgs = string.Join(", ", paramVars.Select(v => "{" + v + "}")); // Interpolated string for display
                
                coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(Matrix)");
                coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(Matrix)");
                GenerateTestRegistration(sb, method, concreteClassName, concreteMethodName, args, formattingArgs, $"{variantSuffix}{classSuffix}({displayArgs})", classFixtures, probeId, classRowStr, isClassDataRow, variantName, cv, mv);

                // Close loops
                for (int i = 0; i < method.CombinatorialValues.Count; i++)
                {
                    indent = indent.Substring(0, indent.Length - 4);
                    sb.AppendLine($"{indent}}}");
                }
            }
            else if (method.IsTheory)
            {
                if (method.TestData.Count > 0)
                {
                    foreach (var dataRow in method.TestData)
                    {
                        int probeId = probeCounter++;
                        string rowString = string.Join(", ", dataRow);
                        // For InlineData, we rely on the rowString being pre-formatted or basic types. 
                        // But if we want formatters to work here, we'd need to cast and format.
                        // Currently InlineData values are injected as literals. 
                        // To support formatters, we would need to wrap the literals? 
                        // Complex: The literal "1" is int. new HexFormatter().Format(1).
                        // Simpler to treat InlineData without formatters for now, OR:
                        // We generated rowString as literals. We can try to wrap them.
                        // But we don't know the types easily here without parsing the literals.
                        // Let's pass 'rowString' as formattingArgs for now (no-op for InlineData unless we parse).
                        coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(Row_{probeId})");
                        coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(Row_{probeId})");
                        GenerateTestRegistration(sb, method, concreteClassName, concreteMethodName, rowString, rowString, $"{variantSuffix}{classSuffix}(Row_{probeId})", classFixtures, probeId, classRowStr, isClassDataRow, variantName, cv, mv);
                    }
                }

                if (method.MemberData.Count > 0)
                {
                    foreach (var md in method.MemberData)
                    {
                        sb.AppendLine($"            // MemberData: {md.MemberName}");
                        string sourceExpr = md.MemberType != null ? md.MemberType + "." + md.MemberName : concreteClassName + "." + md.MemberName;
                        if (md.IsMethod) sourceExpr += "(" + string.Join(", ", md.Parameters) + ")";

                        sb.AppendLine($"            foreach (var dataRow in (global::System.Collections.Generic.IEnumerable<object[]>){sourceExpr})");
                        sb.AppendLine("            {");
                        sb.AppendLine("                if (dataRow != null)");
                        sb.AppendLine("                {");
                        
                        var castArgs = new List<string>();
                        var formattingArgsList = new List<string>();

                        for (int i = 0; i < method.ParameterTypes.Count; i++)
                        {
                            string paramType = method.ParameterTypes[i];
                            for (int j = 0; j < method.ClassTypeParams.Count; j++)
                                paramType = paramType.Replace(method.ClassTypeParams[j], cv[j]);
                            for (int j = 0; j < method.MethodTypeParams.Count; j++)
                                paramType = paramType.Replace(method.MethodTypeParams[j], mv[j]);
                            
                            string castArg = $"({paramType})dataRow[{i}]";
                            castArgs.Add(castArg);

                            string? fmt = method.ParameterFormatters.Count > i ? method.ParameterFormatters[i] : null;
                            if (fmt != null)
                                formattingArgsList.Add($"new {fmt}().Format({castArg})");
                            else
                                formattingArgsList.Add(castArg);
                        }
                        int probeId = probeCounter++;
                        coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(MemberData:{md.MemberName})");
                        coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(MemberData:{md.MemberName})");
                        GenerateTestRegistration(sb, method, concreteClassName, concreteMethodName, string.Join(", ", castArgs), string.Join(", ", formattingArgsList), $"{variantSuffix}{classSuffix}({{string.Join(\", \", dataRow)}})", classFixtures, probeId, classRowStr, isClassDataRow, variantName, cv, mv);
                        sb.AppendLine("                }");
                        sb.AppendLine("            }");
                    }
                }

                if (method.ClassData.Count > 0)
                {
                    foreach (var cdType in method.ClassData)
                    {
                        sb.AppendLine($"            // ClassData: {cdType}");
                        sb.AppendLine($"            foreach (var dataRow in (global::System.Collections.Generic.IEnumerable<object[]>)new {cdType}())");
                        sb.AppendLine("            {");
                        sb.AppendLine("                if (dataRow != null)");
                        sb.AppendLine("                {");
                        
                        var castArgs = new List<string>();
                        var formattingArgsList = new List<string>();

                        for (int i = 0; i < method.ParameterTypes.Count; i++)
                        {
                            string paramType = method.ParameterTypes[i];
                            for (int j = 0; j < method.ClassTypeParams.Count; j++)
                                paramType = paramType.Replace(method.ClassTypeParams[j], cv[j]);
                            for (int j = 0; j < method.MethodTypeParams.Count; j++)
                                paramType = paramType.Replace(method.MethodTypeParams[j], mv[j]);

                            string castArg = $"({paramType})dataRow[{i}]";
                            castArgs.Add(castArg);

                            string? fmt = method.ParameterFormatters.Count > i ? method.ParameterFormatters[i] : null;
                            if (fmt != null)
                                formattingArgsList.Add($"new {fmt}().Format({castArg})");
                            else
                                formattingArgsList.Add(castArg);
                        }
                        int probeId = probeCounter++;
                        coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(ClassData)");
                        coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(ClassData)");
                        GenerateTestRegistration(sb, method, concreteClassName, concreteMethodName, string.Join(", ", castArgs), string.Join(", ", formattingArgsList), $"{variantSuffix}{classSuffix}({{string.Join(\", \", dataRow)}})", classFixtures, probeId, classRowStr, isClassDataRow, variantName, cv, mv);
                        sb.AppendLine("                }");
                        sb.AppendLine("            }");
                    }
                }

                if (method.ClassDataSources.Count > 0)
                {
                    foreach (var cdType in method.ClassDataSources)
                    {
                        sb.AppendLine($"            // ClassDataSource: {cdType}");
                        sb.AppendLine($"            foreach (var dataRow in (global::System.Collections.Generic.IEnumerable<object[]>)TestRunnerExecutor.Services.Get<{cdType}>())");
                        sb.AppendLine("            {");
                        sb.AppendLine("                if (dataRow != null)");
                        sb.AppendLine("                {");
                        
                        var castArgs = new List<string>();
                        var formattingArgsList = new List<string>();

                        for (int i = 0; i < method.ParameterTypes.Count; i++)
                        {
                            string paramType = method.ParameterTypes[i];
                            for (int j = 0; j < method.ClassTypeParams.Count; j++)
                                paramType = paramType.Replace(method.ClassTypeParams[j], cv[j]);
                            for (int j = 0; j < method.MethodTypeParams.Count; j++)
                                paramType = paramType.Replace(method.MethodTypeParams[j], mv[j]);

                            string castArg = $"({paramType})dataRow[{i}]";
                            castArgs.Add(castArg);

                            string? fmt = method.ParameterFormatters.Count > i ? method.ParameterFormatters[i] : null;
                            if (fmt != null)
                                formattingArgsList.Add($"new {fmt}().Format({castArg})");
                            else
                                formattingArgsList.Add(castArg);
                        }
                        int probeId = probeCounter++;
                        coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(ClassDataSource)");
                        coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(ClassDataSource)");
                        GenerateTestRegistration(sb, method, concreteClassName, concreteMethodName, string.Join(", ", castArgs), string.Join(", ", formattingArgsList), $"{variantSuffix}{classSuffix}({{string.Join(\", \", dataRow)}})", classFixtures, probeId, classRowStr, isClassDataRow, variantName, cv, mv);
                        sb.AppendLine("                }");
                        sb.AppendLine("            }");
                    }
                }

                if (method.MethodDataSources.Count > 0)
                {
                    foreach (var md in method.MethodDataSources)
                    {
                        sb.AppendLine($"            // MethodDataSource: {md.MemberName}");
                        string sourceExpr = md.MemberType != null ? $"TestRunnerExecutor.Services.Get<{md.MemberType}>().{md.MemberName}" : $"TestRunnerExecutor.Services.Get<{concreteClassName}>().{md.MemberName}";
                        if (md.IsMethod) sourceExpr += "(" + string.Join(", ", md.Parameters) + ")";

                        sb.AppendLine($"            foreach (var dataRow in (global::System.Collections.Generic.IEnumerable<object[]>){sourceExpr})");
                        sb.AppendLine("            {");
                        sb.AppendLine("                if (dataRow != null)");
                        sb.AppendLine("                {");
                        
                        var castArgs = new List<string>();
                        var formattingArgsList = new List<string>();

                        for (int i = 0; i < method.ParameterTypes.Count; i++)
                        {
                            string paramType = method.ParameterTypes[i];
                            for (int j = 0; j < method.ClassTypeParams.Count; j++)
                                paramType = paramType.Replace(method.ClassTypeParams[j], cv[j]);
                            for (int j = 0; j < method.MethodTypeParams.Count; j++)
                                paramType = paramType.Replace(method.MethodTypeParams[j], mv[j]);
                            
                            string castArg = $"({paramType})dataRow[{i}]";
                            castArgs.Add(castArg);

                            string? fmt = method.ParameterFormatters.Count > i ? method.ParameterFormatters[i] : null;
                            if (fmt != null)
                                formattingArgsList.Add($"new {fmt}().Format({castArg})");
                            else
                                formattingArgsList.Add(castArg);
                        }
                        int probeId = probeCounter++;
                        coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(MethodDataSource:{md.MemberName})");
                        coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(MethodDataSource:{md.MemberName})");
                        GenerateTestRegistration(sb, method, concreteClassName, concreteMethodName, string.Join(", ", castArgs), string.Join(", ", formattingArgsList), $"{variantSuffix}{classSuffix}({{string.Join(\", \", dataRow)}})", classFixtures, probeId, classRowStr, isClassDataRow, variantName, cv, mv);
                        sb.AppendLine("                }");
                        sb.AppendLine("            }");
                    }
                }

                if (method.DIDataSources.Count > 0)
                {
                    foreach (var md in method.DIDataSources)
                    {
                        sb.AppendLine($"            // DIDataSource: {md.MemberType}");
                        string sourceExpr = string.IsNullOrEmpty(md.MemberName) ? $"TestRunnerExecutor.Services.Get<{md.MemberType}>()" : $"TestRunnerExecutor.Services.Get<{md.MemberType}>().{md.MemberName}";
                        if (md.IsMethod) sourceExpr += "()";

                        sb.AppendLine($"            foreach (var dataRow in (global::System.Collections.Generic.IEnumerable<object[]>){sourceExpr})");
                        sb.AppendLine("            {");
                        sb.AppendLine("                if (dataRow != null)");
                        sb.AppendLine("                {");
                        
                        var castArgs = new List<string>();
                        var formattingArgsList = new List<string>();

                        for (int i = 0; i < method.ParameterTypes.Count; i++)
                        {
                            string paramType = method.ParameterTypes[i];
                            for (int j = 0; j < method.ClassTypeParams.Count; j++)
                                paramType = paramType.Replace(method.ClassTypeParams[j], cv[j]);
                            for (int j = 0; j < method.MethodTypeParams.Count; j++)
                                paramType = paramType.Replace(method.MethodTypeParams[j], mv[j]);
                            
                            string castArg = $"({paramType})dataRow[{i}]";
                            castArgs.Add(castArg);

                            string? fmt = method.ParameterFormatters.Count > i ? method.ParameterFormatters[i] : null;
                            if (fmt != null)
                                formattingArgsList.Add($"new {fmt}().Format({castArg})");
                            else
                                formattingArgsList.Add(castArg);
                        }
                        int probeId = probeCounter++;
                        coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(DIDataSource:{md.MemberType})");
                        coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(DIDataSource:{md.MemberType})");
                        GenerateTestRegistration(sb, method, concreteClassName, concreteMethodName, string.Join(", ", castArgs), string.Join(", ", formattingArgsList), $"{variantSuffix}{classSuffix}({{string.Join(\", \", dataRow)}})", classFixtures, probeId, classRowStr, isClassDataRow, variantName, cv, mv);
                        sb.AppendLine("                }");
                        sb.AppendLine("            }");
                    }
                }

                if (method.CustomDataGenerators.Count > 0)
                {
                    foreach (var gen in method.CustomDataGenerators)
                    {
                        sb.AppendLine($"            // CustomDataGenerator: {gen.AttributeType}");
                        string initArgs = string.Join(", ", gen.Arguments);
                        sb.AppendLine($"            foreach (var dataRow in ((DataSourceGeneratorAttribute)new {gen.AttributeType}({initArgs})).GetData())");
                        sb.AppendLine("            {");
                        sb.AppendLine("                if (dataRow != null)");
                        sb.AppendLine("                {");
                        
                        var castArgs = new List<string>();
                        var formattingArgsList = new List<string>();

                        for (int i = 0; i < method.ParameterTypes.Count; i++)
                        {
                            string paramType = method.ParameterTypes[i];
                            for (int j = 0; j < method.ClassTypeParams.Count; j++)
                                paramType = paramType.Replace(method.ClassTypeParams[j], cv[j]);
                            for (int j = 0; j < method.MethodTypeParams.Count; j++)
                                paramType = paramType.Replace(method.MethodTypeParams[j], mv[j]);
                            
                            string castArg = $"({paramType})dataRow[{i}]";
                            castArgs.Add(castArg);

                            string? fmt = method.ParameterFormatters.Count > i ? method.ParameterFormatters[i] : null;
                            if (fmt != null)
                                formattingArgsList.Add($"new {fmt}().Format({castArg})");
                            else
                                formattingArgsList.Add(castArg);
                        }
                        int probeId = probeCounter++;
                        coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(CustomDataGenerator:{gen.AttributeType})");
                        coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}(CustomDataGenerator:{gen.AttributeType})");
                        GenerateTestRegistration(sb, method, concreteClassName, concreteMethodName, string.Join(", ", castArgs), string.Join(", ", formattingArgsList), $"{variantSuffix}{classSuffix}({{string.Join(\", \", dataRow)}})", classFixtures, probeId, classRowStr, isClassDataRow, variantName, cv, mv);
                        sb.AppendLine("                }");
                        sb.AppendLine("            }");
                    }
                }
            }
            else
            {
                int probeId = probeCounter++;
                coverageMetadata.Add($"{concreteClassName}.{concreteMethodName}{variantSuffix}{classSuffix}");
                GenerateTestRegistration(sb, method, concreteClassName, concreteMethodName, "", "", $"{variantSuffix}{classSuffix}", classFixtures, probeId, classRowStr, isClassDataRow, variantName, cv, mv);
            }
        }

        private static void GenerateTestRegistration(StringBuilder sb, TestMethodModel method, string concreteClassName, string concreteMethodName, string args, string? formattingArgs, string displayNameSuffix, List<string> classFixtures, int probeId, string? classRowStr, bool isClassDataRow, string? variantName, string[] cv, string[] mv)
        {
            sb.AppendLine("            list.Add(new ProvaTest");
            sb.AppendLine("            {");

            string displayNameExpr;
            if (method.DisplayNameFormat != null)
            {
                 var fArgs = formattingArgs ?? args;
                 // If args are empty, just use the format string. Otherwise format it.
                 if (string.IsNullOrWhiteSpace(fArgs))
                     displayNameExpr = $"\"{method.DisplayNameFormat}\"";
                 else
                     displayNameExpr = $"string.Format(\"{method.DisplayNameFormat}\", {fArgs})";
            }
            else
            {
                displayNameExpr = "$\"" + concreteClassName + "." + concreteMethodName + displayNameSuffix + "\"";
            }
            
            sb.AppendLine($"                DisplayName = {displayNameExpr},");
            sb.AppendLine($"                FullName = $\"{concreteClassName}.{concreteMethodName}\",");
            sb.AppendLine($"                ClassName = \"{concreteClassName}\",");
            sb.AppendLine($"                CoverageId = {probeId},");
            sb.AppendLine($"                Description = {(method.Description != null ? $"\"{method.Description.Replace("\"", "\\\"")}\"" : "null")},");
            sb.AppendLine($"                SkipReason = {(method.SkipReason != null ? $"\"{method.SkipReason.Replace("\"", "\\\"")}\"" : "null")},");
            sb.AppendLine($"                RetryCount = {(method.RetryCount.HasValue ? method.RetryCount.Value.ToString(global::System.Globalization.CultureInfo.InvariantCulture) : "null")},");
            sb.AppendLine($"                MaxParallel = {(method.MaxParallel.HasValue ? method.MaxParallel.Value.ToString(global::System.Globalization.CultureInfo.InvariantCulture) : "null")},");
            sb.AppendLine($"                DoNotParallelize = {(method.DoNotParallelize ? "true" : "false")},");
            sb.AppendLine($"                Repeat = {(method.RepeatCount.HasValue ? method.RepeatCount.Value.ToString(global::System.Globalization.CultureInfo.InvariantCulture) : "null")},");
            sb.AppendLine($"                Timeout = {(method.TimeoutMs.HasValue ? method.TimeoutMs.Value.ToString(global::System.Globalization.CultureInfo.InvariantCulture) : "null")},");
            sb.AppendLine($"                Culture = {(method.Culture != null ? $"\"{method.Culture}\"" : "null")},");
            sb.AppendLine($"                ExecutorType = {(method.TestExecutorType != null ? $"typeof({method.TestExecutorType})" : "null")},");
            sb.AppendLine($"                Variant = {(variantName != null ? $"\"{variantName}\"" : "null")},");

            if (method.ClassBefore.Count > 0)
                sb.AppendLine($"                ClassBefore = new Func<Task>[] {{ {string.Join(", ", method.ClassBefore.Select(h => h.IsAsync ? $"async () => await {concreteClassName}.{h.Name}()" : $"() => {{ {concreteClassName}.{h.Name}(); return Task.CompletedTask; }}"))} }},");
            if (method.ClassAfter.Count > 0)
                sb.AppendLine($"                ClassAfter = new Func<Task>[] {{ {string.Join(", ", method.ClassAfter.Select(h => h.IsAsync ? $"async () => await {concreteClassName}.{h.Name}()" : $"() => {{ {concreteClassName}.{h.Name}(); return Task.CompletedTask; }}"))} }},");
            
            if (classFixtures.Count > 0)
                sb.AppendLine($"                ClassFixtures = new Func<Task>[] {{ {string.Join(", ", classFixtures.Select(f => $"async () => {{ var f = TestRunnerExecutor.Services.Get<{f}>(); if ((object)f is IAsyncLifetime al) await al.InitializeAsync(); }}"))} }},");

            if (method.ResourceConstraints != null && method.ResourceConstraints.Count > 0)
                sb.AppendLine($"                ResourceConstraints = new string[] {{ {string.Join(", ", method.ResourceConstraints.Select(r => $"\"{r}\""))} }},");

            if (method.ParallelLimiters != null && method.ParallelLimiters.Count > 0)
                sb.AppendLine($"                ParallelLimiters = new (string, int)[] {{ {string.Join(", ", method.ParallelLimiters.Select(l => $"(\"{l.Key}\", {l.Limit})"))} }},");

            if (!string.IsNullOrEmpty(method.ParallelGroup))
                sb.AppendLine($"                ParallelGroup = \"{method.ParallelGroup}\",");

            if (method.Properties.Count > 0)
                sb.AppendLine("                Properties = new Dictionary<string, string> { " + string.Join(", ", method.Properties.Select(p => $"{{ \"{p.Key}\", \"{p.Value}\" }}")) + " },");
            sb.AppendLine("                ExecuteDelegate = async () => {");
            if (!method.IsStatic)
            {
                sb.AppendLine($"                    {concreteClassName}? instance = null;");
            }
            sb.AppendLine($"                    CoverageRegistry.Hit({probeId});");
            sb.AppendLine("                    var originalCulture = global::System.Globalization.CultureInfo.CurrentCulture;");
            sb.AppendLine("                    var originalUICulture = global::System.Globalization.CultureInfo.CurrentUICulture;");
            sb.AppendLine();
            if (method.UsesOutputHelper)
            {
                 sb.AppendLine("                    var outputHelper = new Prova.TestOutputHelper();");
            }

            sb.AppendLine("                    try {");
            if (!string.IsNullOrEmpty(method.Culture))
            {
                sb.AppendLine($"                        var culture = new global::System.Globalization.CultureInfo(\"{method.Culture}\");");
                sb.AppendLine("                        global::System.Globalization.CultureInfo.CurrentCulture = culture;");
                sb.AppendLine("                        global::System.Globalization.CultureInfo.CurrentUICulture = culture;");
            }

            if (method.IsStatic)
            {
                 sb.AppendLine("                    try {");
                  {
                      if (method.ReturnsVoid)
                          sb.AppendLine($"                        {concreteClassName}.{concreteMethodName}({args});");
                      else
                          sb.AppendLine($"                        await {concreteClassName}.{concreteMethodName}({args});");
                  }
                 sb.AppendLine("                    } finally { }");
            }
            else
            {
                foreach (var fixtureType in classFixtures)
                {
                    var varName = $"fixture_{fixtureType.Replace(".", "_")}";
                    sb.AppendLine($"                    var {varName} = TestRunnerExecutor.Services.Get<{fixtureType}>();");
                }
                
                var constructorArgs = new List<string>();
                int classDataIdx = 0;
                for (int i = 0; i < method.Dependencies.Count; i++)
                {
                    var dep = method.Dependencies[i];
                    var paramType = method.ConstructorParameterTypes.Count > i ? method.ConstructorParameterTypes[i] : "object";

                    if (dep.StartsWith("__CLASS_DATA_", StringComparison.Ordinal))
                    {
                        if (classRowStr != null)
                        {
                             if (isClassDataRow)
                                 constructorArgs.Add($"({paramType}){classRowStr}[{classDataIdx}]"); 
                             else
                                 constructorArgs.Add(classRowStr.Split(',')[classDataIdx].Trim());
                        }
                        else
                        {
                             constructorArgs.Add("default"); 
                        }
                        classDataIdx++;
                    }
                    else if (dep == "outputHelper")
                    {
                        constructorArgs.Add("outputHelper");
                    }
                    else
                    {
                        constructorArgs.Add(dep);
                    }
                }

                if (method.ClassFactoryType != null)
                {
                    sb.AppendLine($"                    var factory = TestRunnerExecutor.Services.Get<{method.ClassFactoryType}>();");
                    sb.AppendLine($"                    instance = factory.CreateInstance(TestRunnerExecutor.Services);");
                }
                else
                {
                    sb.AppendLine($"                    instance = new {concreteClassName}({string.Join(", ", constructorArgs)});");
                }
                sb.AppendLine("                    try {");
                
                if (method.LifecycleBefore.Count > 0)
                {
                    sb.AppendLine("                        // Lifecycle: Before");
                    foreach (var hook in method.LifecycleBefore) 
                    {
                        string executorType = hook.ExecutorType != null ? $"typeof({hook.ExecutorType})" : "null";
                        string hookAction = hook.IsAsync ? $"async () => await instance.{hook.Name}()" : $"() => {{ instance.{hook.Name}(); return global::System.Threading.Tasks.Task.CompletedTask; }}";
                        sb.AppendLine($"                        await TestRunnerExecutor.InvokeHookHelper({hookAction}, \"{hook.Name}\", {executorType});");
                    }
                }
                
                if (method.ImplementsAsyncLifetime) sb.AppendLine("                        if ((object)instance is IAsyncLifetime asyncLife) await asyncLife.InitializeAsync();");

                if (method.MaxAllocBytes.HasValue)
                {
                    sb.AppendLine($"                        long maxAlloc = {method.MaxAllocBytes.Value};");
                    sb.AppendLine("                        long startAlloc = global::System.GC.GetAllocatedBytesForCurrentThread();");
                }

                  {
                      if (method.IsFsCheckProperty)
                      {
                        var resolvedTypes = new global::System.Collections.Generic.List<string>();
                        for (int i = 0; i < method.ParameterTypes.Count; i++)
                        {
                            string paramType = method.ParameterTypes[i];
                            for (int j = 0; j < method.ClassTypeParams.Count; j++) paramType = paramType.Replace(method.ClassTypeParams[j], cv[j]);
                            for (int j = 0; j < method.MethodTypeParams.Count; j++) paramType = paramType.Replace(method.MethodTypeParams[j], mv[j]);
                            resolvedTypes.Add(paramType);
                        }
                        var typeArgs = string.Join(", ", resolvedTypes);
                        var pVars = global::System.Linq.Enumerable.Range(0, resolvedTypes.Count).Select(k => $"p{k}").ToList();
                        var pDecl = "(" + string.Join(", ", pVars) + ")";
                        var pCall = string.Join(", ", pVars);
                        
                        sb.AppendLine($"                    var fsCheckProp = global::FsCheck.Prop.ForAll<{typeArgs}>({pDecl} => {{");
                         if (method.ReturnsVoid)
                              sb.AppendLine($"                        instance.{concreteMethodName}({pCall});");
                          else
                              sb.AppendLine($"                        instance.{concreteMethodName}({pCall}).GetAwaiter().GetResult();");
                        sb.AppendLine("                    });");
                        
                        sb.AppendLine("                    var fsConfig = new global::System.Collections.Generic.Dictionary<string, string>();");
                         if (method.FsCheckConfig != null)
                             foreach(var kvp in method.FsCheckConfig) sb.AppendLine($"                    fsConfig[\"{kvp.Key}\"] = \"{kvp.Value}\";");

                        sb.AppendLine("                    Prova.FsCheck.FsCheckRunner.Run(fsConfig, fsCheckProp);");
                      }
                      else
                      {
                          if (method.ReturnsVoid)
                              sb.AppendLine($"                        instance.{concreteMethodName}({args});");
                          else
                              sb.AppendLine($"                        await instance.{concreteMethodName}({args});");
                      }
                  }

                if (method.MaxAllocBytes.HasValue)
                {
                    sb.AppendLine("                        long endAlloc = global::System.GC.GetAllocatedBytesForCurrentThread();");
                    sb.AppendLine("                        if (endAlloc - startAlloc > maxAlloc) throw new global::System.Exception($\"Memory allocation exceeded: {endAlloc - startAlloc} > {maxAlloc}\");");
                }

                if (method.MockFields.Count > 0)
                {
                    foreach (var mockName in method.MockFields) sb.AppendLine($"                        instance.{mockName}.VerifyAll();");
                }

                sb.AppendLine("                    } finally {");

                if (method.LifecycleAfter.Count > 0)
                {
                    sb.AppendLine("                        // Lifecycle: After");
                    foreach (var hook in method.LifecycleAfter)
                    {
                        string executorType = hook.ExecutorType != null ? $"typeof({hook.ExecutorType})" : "null";
                        string hookAction = hook.IsAsync ? $"async () => await instance.{hook.Name}()" : $"() => {{ instance.{hook.Name}(); return global::System.Threading.Tasks.Task.CompletedTask; }}";
                        sb.AppendLine($"                        try {{ await TestRunnerExecutor.InvokeHookHelper({hookAction}, \"{hook.Name}\", {executorType}); }} catch {{ }}");
                    }
                }
                if (method.ImplementsAsyncLifetime) sb.AppendLine("                        if ((object)instance is IAsyncLifetime asyncLifeDisp) await asyncLifeDisp.DisposeAsync();");
                sb.AppendLine("                        if ((object)instance is global::System.IDisposable d) d.Dispose();");
                sb.AppendLine("                    }");
            }
                sb.AppendLine("                    } finally {");
                sb.AppendLine("                        global::System.Globalization.CultureInfo.CurrentCulture = originalCulture;");
                sb.AppendLine("                        global::System.Globalization.CultureInfo.CurrentUICulture = originalUICulture;");
                sb.AppendLine("                    }");
                sb.AppendLine($"                    return {(method.UsesOutputHelper ? "outputHelper.Output" : "null")};");
                sb.AppendLine("                }");
            sb.AppendLine("            });");
        }
        private static string RemoveGenerics(string name)
        {
            int idx = name.LastIndexOf('<');
            return idx != -1 ? name.Substring(0, idx) : name;
        }
    }

}
